"""
Train the Sketch→Image decoder on Modal.

Takes pre-trained BrailleNet encoder + trains SketchDecoder to generate
images from stroke embeddings.

Training data:
  - Input: QuickDraw stroke sequences (from quickdraw_data.py)
  - Target: Images generated by SD 1.5 from the rasterized sketches

The decoder learns: BrailleNet_embeddings → realistic_image

Usage:
    modal run train/modal_train_decoder.py
"""

import modal

app = modal.App("sketch-decoder-train")

train_image = (
    modal.Image.debian_slim(python_version="3.11")
    .pip_install(
        "torch==2.3.1",
        "torchvision==0.18.1",
        "numpy>=1.24.0",
        "Pillow>=10.0.0",
        "diffusers>=0.28.0",
        "transformers>=4.40.0",
        "accelerate>=0.30.0",
    )
)

data_volume = modal.Volume.from_name("braillenet-data", create_if_missing=True)
model_volume = modal.Volume.from_name("braillenet-models", create_if_missing=True)


def generate_target_images(data_dir: str, output_dir: str,
                           batch_size: int = 16, max_samples: int = 50000):
    """Generate target images from rasterized sketches using SD 1.5.

    This creates (sketch_strokes, target_image) pairs for decoder training.
    """
    import os
    from pathlib import Path

    import torch
    from diffusers import StableDiffusionControlNetPipeline, ControlNetModel
    from diffusers import DPMSolverMultistepScheduler
    from PIL import Image
    from torchvision import transforms

    device = torch.device("cuda")
    data_path = Path(data_dir)
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    # Load ControlNet + SD 1.5
    print("Loading ControlNet pipeline...")
    controlnet = ControlNetModel.from_pretrained(
        "lllyasviel/control_v11p_sd15_scribble",
        torch_dtype=torch.float16,
    )
    pipe = StableDiffusionControlNetPipeline.from_pretrained(
        "stable-diffusion-v1-5/stable-diffusion-v1-5",
        controlnet=controlnet,
        torch_dtype=torch.float16,
        safety_checker=None,
    )
    pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
    pipe.to(device)
    pipe.set_progress_bar_config(disable=True)
    print("Pipeline ready!")

    # Process rasters
    raster_dir = data_path / "rasters"
    categories = sorted(d.name for d in raster_dir.iterdir() if d.is_dir())

    count = 0
    for cat in categories:
        cat_dir = raster_dir / cat
        cat_out = out_path / cat
        cat_out.mkdir(parents=True, exist_ok=True)

        prompt = f"a beautiful detailed illustration of a {cat.replace('_', ' ')}, " \
                 f"professional art, vivid colors, masterpiece"

        files = sorted(cat_dir.glob("*.png"))[:max_samples // len(categories)]

        for i in range(0, len(files), batch_size):
            batch_files = files[i:i + batch_size]
            images = []
            for f in batch_files:
                img = Image.open(f).convert("RGB").resize((512, 512))
                images.append(img)

            with torch.inference_mode():
                results = pipe(
                    prompt=[prompt] * len(images),
                    image=images,
                    num_inference_steps=20,
                    guidance_scale=7.5,
                    controlnet_conditioning_scale=0.8,
                ).images

            for f, result in zip(batch_files, results):
                result.save(cat_out / f.name)
                count += 1

            if count % 100 == 0:
                print(f"  Generated {count} target images...")

        if count >= max_samples:
            break

    print(f"Generated {count} target images → {out_path}")
    return count


@app.function(
    image=train_image,
    gpu="H100",
    timeout=21600,  # 6 hours
    volumes={"/data": data_volume, "/models": model_volume},
)
def train_decoder(
    num_epochs: int = 30,
    batch_size: int = 32,
    lr: float = 1e-4,
    d_model: int = 256,
    nhead: int = 8,
    num_layers: int = 6,
    max_points: int = 512,
    image_size: int = 512,
    generate_targets: bool = True,
    max_train_samples: int = 50000,
    perceptual_weight: float = 1.0,
    l1_weight: float = 10.0,
):
    import json
    import time
    from pathlib import Path

    import numpy as np
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
    from torch.utils.data import DataLoader, Dataset
    from torchvision import transforms
    from PIL import Image

    device = torch.device("cuda")
    print(f"Device: {device} ({torch.cuda.get_device_name()})")

    # =================================================================
    # STEP 1: Generate target images if needed
    # =================================================================
    targets_dir = Path("/data/targets")
    if generate_targets and not (targets_dir / "done.flag").exists():
        print("\n=== Generating target images with ControlNet ===")
        generate_target_images(
            "/data", str(targets_dir),
            batch_size=8, max_samples=max_train_samples,
        )
        (targets_dir / "done.flag").touch()
        data_volume.commit()
        print("Target generation complete!\n")
    else:
        print("Target images already exist, skipping generation.")

    # =================================================================
    # STEP 2: Build dataset
    # =================================================================

    class SketchImageDataset(Dataset):
        """Paired (strokes, target_image) dataset."""

        def __init__(self, data_dir: str, targets_dir: str,
                     max_points: int = 512, image_size: int = 512):
            self.max_points = max_points
            self.image_size = image_size
            self.pairs = []

            strokes_path = Path(data_dir) / "strokes"
            targets_path = Path(targets_dir)

            self.img_transform = transforms.Compose([
                transforms.Resize(image_size),
                transforms.CenterCrop(image_size),
                transforms.ToTensor(),
            ])

            for cat_dir in sorted(strokes_path.iterdir()):
                if not cat_dir.is_dir():
                    continue
                cat_name = cat_dir.name
                target_cat = targets_path / cat_name

                if not target_cat.exists():
                    continue

                for npz_file in sorted(cat_dir.glob("*.npz")):
                    target_img = target_cat / (npz_file.stem + ".png")
                    if target_img.exists():
                        self.pairs.append((npz_file, target_img))

            print(f"Dataset: {len(self.pairs)} stroke-image pairs")

        def __len__(self):
            return len(self.pairs)

        def __getitem__(self, idx):
            stroke_file, img_file = self.pairs[idx]

            # Load strokes
            data = np.load(stroke_file)
            points = data["points"].astype(np.float32)
            T = len(points)
            if T > self.max_points:
                points = points[:self.max_points]
                T = self.max_points

            mask = np.ones(self.max_points, dtype=np.bool_)
            if T < self.max_points:
                padded = np.full((self.max_points, 2), -2.0, dtype=np.float32)
                padded[:T] = points
                points = padded
                mask[T:] = False

            # Load target image
            img = Image.open(img_file).convert("RGB")
            img_tensor = self.img_transform(img)

            return {
                "points": torch.from_numpy(points),
                "mask": torch.from_numpy(mask),
                "target": img_tensor,
            }

    # =================================================================
    # STEP 3: Load pre-trained BrailleNet encoder
    # =================================================================

    # Import encoder architecture (inline to work in Modal)
    class StrokeEncoder(nn.Module):
        def __init__(self, d_model=256, nhead=8, num_layers=6, max_points=512):
            super().__init__()
            self.d_model = d_model
            self.point_proj = nn.Sequential(
                nn.Linear(4, d_model), nn.GELU(), nn.Linear(d_model, d_model),
            )
            self.pos_encoding = nn.Parameter(
                torch.randn(1, max_points, d_model) * 0.02
            )
            encoder_layer = nn.TransformerEncoderLayer(
                d_model=d_model, nhead=nhead, dim_feedforward=d_model * 4,
                dropout=0.1, batch_first=True, activation='gelu',
            )
            self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
            self.norm = nn.LayerNorm(d_model)

        def forward(self, points, mask):
            B, T, _ = points.shape
            is_sep = ((points[:, :, 0] == -1) & (points[:, :, 1] == -1)).float().unsqueeze(-1)
            is_pad = ((points[:, :, 0] == -2) & (points[:, :, 1] == -2)).float().unsqueeze(-1)
            xy = points.clone()
            xy[~mask] = 0.0
            xy[(is_sep.squeeze(-1) > 0.5)] = 0.0
            features = torch.cat([xy, is_sep, is_pad], dim=-1)
            h = self.point_proj(features)
            h = h + self.pos_encoding[:, :T, :]
            h = self.transformer(h, src_key_padding_mask=~mask)
            return self.norm(h)

    # Load pre-trained encoder
    encoder = StrokeEncoder(d_model=d_model, nhead=nhead,
                            num_layers=num_layers, max_points=max_points)

    pretrained_path = Path("/models/braillenet_pretrained.pth")
    if pretrained_path.exists():
        checkpoint = torch.load(pretrained_path, map_location="cpu")
        encoder.load_state_dict(checkpoint["model_state_dict"])
        print(f"Loaded pre-trained encoder (loss={checkpoint.get('loss', '?')})")
    else:
        print("WARNING: No pre-trained encoder found! Training from scratch.")

    encoder = encoder.to(device)
    encoder.eval()  # Freeze encoder
    for p in encoder.parameters():
        p.requires_grad = False

    # =================================================================
    # STEP 4: Build decoder
    # =================================================================

    # Inline decoder (same as sketch_decoder.py)
    class SpatialProjection(nn.Module):
        def __init__(self, d_model=256, spatial_size=16, out_channels=256):
            super().__init__()
            self.spatial_size = spatial_size
            self.out_channels = out_channels
            num_tokens = spatial_size * spatial_size
            self.spatial_queries = nn.Parameter(torch.randn(1, num_tokens, d_model) * 0.02)
            self.cross_attn = nn.MultiheadAttention(d_model, 8, batch_first=True, dropout=0.1)
            self.norm = nn.LayerNorm(d_model)
            self.proj = nn.Linear(d_model, out_channels)

        def forward(self, embeddings, mask=None):
            B = embeddings.shape[0]
            queries = self.spatial_queries.expand(B, -1, -1)
            kpm = ~mask if mask is not None else None
            attn_out, _ = self.cross_attn(queries, embeddings, embeddings, key_padding_mask=kpm)
            attn_out = self.norm(attn_out + queries)
            spatial = self.proj(attn_out).permute(0, 2, 1)
            return spatial.view(B, self.out_channels, self.spatial_size, self.spatial_size)

    class ResBlock(nn.Module):
        def __init__(self, c):
            super().__init__()
            self.net = nn.Sequential(
                nn.Conv2d(c, c, 3, 1, 1), nn.InstanceNorm2d(c, affine=True), nn.GELU(),
                nn.Conv2d(c, c, 3, 1, 1), nn.InstanceNorm2d(c, affine=True),
            )
        def forward(self, x): return x + self.net(x)

    class UpsampleBlock(nn.Module):
        def __init__(self, in_c, out_c):
            super().__init__()
            self.net = nn.Sequential(
                nn.Upsample(scale_factor=2, mode="nearest"),
                nn.Conv2d(in_c, out_c, 3, 1, 1),
                nn.InstanceNorm2d(out_c, affine=True),
                nn.GELU(),
            )
        def forward(self, x): return self.net(x)

    class SketchDecoder(nn.Module):
        def __init__(self, d_model=256, base_channels=256):
            super().__init__()
            self.spatial_proj = SpatialProjection(d_model, 16, base_channels)
            self.res_blocks = nn.Sequential(*[ResBlock(base_channels) for _ in range(4)])
            self.upsample = nn.Sequential(
                UpsampleBlock(base_channels, 256),
                UpsampleBlock(256, 128),
                UpsampleBlock(128, 64),
                UpsampleBlock(64, 32),
                UpsampleBlock(32, 16),
            )
            self.to_rgb = nn.Sequential(
                nn.Conv2d(16, 16, 3, 1, 1), nn.GELU(),
                nn.Conv2d(16, 3, 1), nn.Sigmoid(),
            )

        def forward(self, embeddings, mask=None):
            x = self.spatial_proj(embeddings, mask)
            x = self.res_blocks(x)
            x = self.upsample(x)
            return self.to_rgb(x)

    decoder = SketchDecoder(d_model=d_model).to(device)
    dec_params = sum(p.numel() for p in decoder.parameters())
    print(f"Decoder parameters: {dec_params:,}")

    # =================================================================
    # STEP 5: Perceptual loss
    # =================================================================
    from torchvision.models import vgg16, VGG16_Weights
    vgg = vgg16(weights=VGG16_Weights.IMAGENET1K_V1).features[:23].to(device).eval()
    for p in vgg.parameters():
        p.requires_grad = False

    vgg_mean = torch.tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1).to(device)
    vgg_std = torch.tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1).to(device)

    def perceptual_loss(pred, target):
        pred_n = (pred - vgg_mean) / vgg_std
        tgt_n = (target - vgg_mean) / vgg_std
        return F.l1_loss(vgg(pred_n), vgg(tgt_n))

    # =================================================================
    # STEP 6: Train
    # =================================================================
    dataset = SketchImageDataset("/data", str(targets_dir),
                                 max_points=max_points, image_size=image_size)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True,
                        num_workers=4, drop_last=True, pin_memory=True)

    optimizer = torch.optim.AdamW(decoder.parameters(), lr=lr, weight_decay=0.01)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=num_epochs * len(loader),
    )

    best_loss = float("inf")
    start_time = time.time()

    print(f"\nTraining: {num_epochs} epochs, {len(dataset)} samples")
    print(f"  L1 weight={l1_weight}, perceptual weight={perceptual_weight}")

    for epoch in range(num_epochs):
        decoder.train()
        epoch_loss = 0
        epoch_l1 = 0
        epoch_perc = 0
        num_batches = 0

        for batch in loader:
            points = batch["points"].to(device)
            mask = batch["mask"].to(device)
            target = batch["target"].to(device)

            # Encode strokes (frozen)
            with torch.no_grad():
                embeddings = encoder(points, mask)

            # Decode to image
            pred = decoder(embeddings, mask)

            # Losses
            l1 = F.l1_loss(pred, target)
            perc = perceptual_loss(pred, target)
            loss = l1 * l1_weight + perc * perceptual_weight

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(decoder.parameters(), 1.0)
            optimizer.step()
            scheduler.step()

            epoch_loss += loss.item()
            epoch_l1 += l1.item()
            epoch_perc += perc.item()
            num_batches += 1

        avg_loss = epoch_loss / num_batches
        avg_l1 = epoch_l1 / num_batches
        avg_perc = epoch_perc / num_batches
        elapsed = time.time() - start_time

        print(f"Epoch {epoch+1}/{num_epochs} ({elapsed/60:.1f}min) | "
              f"loss={avg_loss:.4f} L1={avg_l1:.4f} perc={avg_perc:.4f}")

        if avg_loss < best_loss:
            best_loss = avg_loss
            torch.save({
                "epoch": epoch,
                "decoder_state_dict": decoder.state_dict(),
                "loss": best_loss,
                "config": {
                    "d_model": d_model,
                    "image_size": image_size,
                    "decoder_params": dec_params,
                },
            }, "/models/sketch_decoder_best.pth")
            print(f"  → Saved best decoder")

    # Save final
    total_time = time.time() - start_time
    torch.save({
        "epoch": num_epochs,
        "decoder_state_dict": decoder.state_dict(),
        "encoder_config": {
            "d_model": d_model, "nhead": nhead,
            "num_layers": num_layers, "max_points": max_points,
        },
        "training_time_s": total_time,
        "best_loss": best_loss,
    }, "/models/sketch_decoder_final.pth")
    model_volume.commit()

    print(f"\nDone in {total_time/3600:.2f} hours. Best loss: {best_loss:.4f}")
    return {"best_loss": best_loss, "time_h": total_time / 3600, "params": dec_params}


@app.local_entrypoint()
def main():
    result = train_decoder.remote()
    print(f"\nResult: {result}")
